name = "Cactus"
license = "MIT"
licenselink = "https://github.com/baradhiren/hugo-theme/blob/main/LICENSE"
description = "A clean, responsive hugo theme for personal blog. Forked from hugo theme cactus created by @monkeyWzr."
homepage = "https://github.com/baradhiren/hugo-theme"
tags = ["blog", "responsive", "clean"]
features = ["mathjax", "customizable", "color"]
min_version = "0.55"

# If the theme has a single author
[author]
    name = "Hiren Barad"
    homepage = "https://github.com/baradhiren"

# If porting an existing theme
[original]
    author = "Zeran Wu"
    homepage = "https://github.com/monkeyWzr"
    repo = "https://github.com/monkeyWzr/hugo-theme-cactus"